schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "multires_transpose"
version = "2.0.0"
name = "Multires  Transpose"
tagline = "Edit multiple multiresolution meshes through a single mesh"
maintainer = "4ColorGrafix <4colorgrafix@gmail.com>"
# Supported types: "add-on", "theme"
type = "add-on"

# # Optional: link to documentation, support, source files, etc
# website = 

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["System", "User Interface"]

blender_version_min = "4.5.5"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:MIT",
]